### ISSUE TITLE
ProcessManager locking Router dispatch (apparently)

### ISSUE THREAD

**Issue by y86** [commanded/commanded#170]
The process manager is apparently locking the dispatch process of a command - I am getting a `:consistency_timeout` from the Router (timeout set to 15 seconds on test `env` that is more than enough for all listeners to finish). 

I've disabled all event listeners but the Process Manager - to make sure the issue wasn't any of the projectors - and the timeout persists. 

Can someone please take a look on my Process Manager and let me know if I am missing any important detail on the Manager configuration or if indeed it is a problem with the Manager?

The code below creates 4 stages in sequence. The last stage created has the field `next_stage_id: nil` and its event is not handled (it goes into the clause of the `interested?/1` function that should stop the manager).
```
defmodule MyApp.Methodologies.ProcessManagers.CreateGroupStagesProcess do
  use Commanded.ProcessManagers.ProcessManager,
    name: "Methodologies.ProcessManagers.CreateGroupStagesProcess",
    consistency: Application.get_env(:commanded, :consistency),
    router: MyApp.Methodologies.Router

  alias MyApp.Methodologies
  alias MyApp.Methodologies.ProcessManagers.CreateGroupStagesProcess
  alias MyApp.Methodologies.Commands.{
    CreateStage,
    SetNextStageId,
  }
  alias MyApp.Methodologies.Events.{
    GroupCreated,
    StageCreated
  }
  alias MyApp.Methodologies.Projections.Group

  defstruct [
    group_id: "",
    methodology: "",
    remaining_stage_types: [],
  ]

  def interested?(%GroupCreated{group_id: group_id}), do: {:start, group_id}
  def interested?(%StageCreated{group_id: group_id, next_stage_id: nil}), do: {:stop, group_id}
  def interested?(%StageCreated{group_id: group_id}), do: {:continue, group_id}
  def interested?(_event), do: false


  def handle(
    %CreateGroupStagesProcess{},
    %GroupCreated{group_id: group_id, methodology: methodology}
  ) do
    group = %Group{id: group_id, methodology: methodology}

    [first_stage | remaining_stage_types] = Methodologies.list_methodology_stages(group)
    next_stage_id = last_stage_id(remaining_stage_types)

    CreateStage.create(%{type: first_stage, previous_stage_id: nil, next_stage_id: next_stage_id}, group)
  end

  def handle(
    %CreateGroupStagesProcess{
      group_id: group_id, 
      methodology: methodology,
      remaining_stage_types: [next_stage_type | remaining_stage_types]}, 
    %StageCreated{group_id: group_id, stage_id: stage_id}
  ) do
    group = %Group{id: group_id, methodology: methodology}
    next_stage_id = last_stage_id(remaining_stage_types)

    create_stage = 
      CreateStage.create(%{type: next_stage_type, previous_stage_id: stage_id, next_stage_id: next_stage_id}, group)
    set_next_stage_id_of_previous_stage = 
      %SetNextStageId{stage_id: stage_id, next_stage_id: create_stage.stage_id}

    [create_stage, set_next_stage_id_of_previous_stage]
  end


  ## state mutators
  def apply(
    %CreateGroupStagesProcess{} = process, 
    %GroupCreated{group_id: group_id, methodology: methodology}
  ) do
    [_ | remaining_stage_types] = Methodologies.list_methodology_stages(methodology)
    %CreateGroupStagesProcess{process |
      group_id: group_id,
      methodology: methodology,
      remaining_stage_types: remaining_stage_types
    }
  end

  def apply(
    %CreateGroupStagesProcess{
      group_id: group_id,
      remaining_stage_types: [_ | remaining_stage_types]} = process, 
    %StageCreated{group_id: group_id}
  ) do
    %CreateGroupStagesProcess{process | remaining_stage_types: remaining_stage_types}
  end

  ## private helpers
  defp last_stage_id([]), do: nil
  defp last_stage_id([_|_]), do: ""
end
```

**Comment by slashdotdash** [comment]
@y86 Your process manager looks fine. It looks as though there's an issue when a process manager is configured using `:strong` consistency due to changes implemented in #141 to support routing to multiple process instances. 

I've created and merged a pull request with a fix (#171). 

Can you try your code using the lastest Commanded master branch, referenced from GitHub (configured in `mix.exs` as below)?

```elixir
defp deps do
  {:commanded, github: "commanded/commanded"}
end
```

**Comment by y86** [comment]
@slashdotdash, I tried the version on the master branch and it no longer gave me a `:consistency_timeout`. However, I didn't get the behavior I was expecting.

The ProccessManagers should have created 4 stages, but it only created one and resumed the code. I was expecting that the `:strong` consistency would wait for the process manager to end (with the `{:stop, uuid}`) in order to resume.
if that is the expected behavior, then it seems there is still a problem.

**Comment by slashdotdash** [comment]
@y86 The behaviour you're seeing is by design. You should find that the other stages get created eventually, at some point later after the initial command dispatch. 

When you configure a process manager with `:strong` consistency it will ensure that any commands created by the process manager have been successfully dispatched, but it dispatches those commands using _eventual_ consistency. This is likely not what you expected, sorry. It's a limitation of the current implementation of process managers to prevent deadlocks.

An issue has been created to rework process managers to allow them to be event sourced, as aggregates currently are (#137). I will look to see whether it's possible to address the consistency issue with those changes.
