### ISSUE TITLE
Process manager stops if `interested?/1` returns an empty list

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#185]
When a process manager receives `{:start, []}`, `{:continue, []}`, or `{:stop, process_uuid}` it should just acknowledge receipt of the event and continue since it has nothing to do.

**Comment by janpieper** [comment]
Can you provide more details on that issue, because I cannot reproduce it...

* `{:start, []}` --> no process manager instances
* `{:start, []}` + `{:start, []}` --> no process manager instances
* `{:start, "foo"}` --> one process manager instance
* `{:start, "foo"}` + `{:continue, []}` --> one process manager instance
* `{:continue, []}` --> no process manager instances (because of #181)

And I think `{:stop, process_uuid}` should stop the process manager, right? :smiley:

**Comment by slashdotdash** [comment]
If an empty list is returned by the `interested?/1` function then the process manager will become stuck because the event is never acknowledged. The process manager assumes the event has been delegated to an instance, which will ack the event after successsful processing. However this won't happen when there are no instances handling the event (because of the empty list).

To test this you need to first have an event return `{:start, []}` or `{:continue, []}` and then a second event to be processed by an instance. You should find that the second event is _never_ handled. That's the problem.
