### ISSUE TITLE
When is EventStore.subscribe called?

### ISSUE THREAD

**Issue by drozzy** [commanded/commanded#197]
Just curious when is `subscribe` actually called? I can't seem to find a correspondence between hydrating an aggregate and calling a subscribe function.

**Comment by slashdotdash** [comment]
An aggregate instance subscribes to its own event stream in the [`GenServer.init/1` callback function](https://github.com/commanded/commanded/blob/6babdb1daf8c72f573af05656eae7e6d94e83a43/lib/commanded/aggregates/aggregate.ex#L87). 

The reason for doing this is to support multi-node deployment when distributed Erlang is _not_ used. In this setup the same aggregate instance may run as a process on multiple nodes. When events are appended to the event store by an aggregate on one node they are published to any other running instance so that it can mutate its own state. This helps ensure multiple processes for the same aggregate instance will eventually have identical state, regardless of which process handles a command. The event store also provides optimistic concurrency control by validating the expected stream version when appending events. This is to guard against the scenario where concurrent commands are handled by two processes running on different nodes.

**Comment by drozzy** [comment]
I see. They are two different subscribes - the one I was looking for was for event handlers probably.
