### ISSUE TITLE
Current meaning of correlation and causation IDs in Commanded

### ISSUE THREAD

**Issue by aef** [commanded/commanded#232]
Please see my question here: https://stackoverflow.com/q/53740867/322863

**Comment by slashdotdash** [comment]
Commanded has implemented [correlation and causation ids](https://github.com/commanded/commanded/blob/master/guides/Commands.md#correlation-and-causation-ids) as described in the guides, copied below.

By default commands *will not* be persisted, therefore you cannot follow the chain of cause and affect from command > event > command unless you also persist incoming commands. You can use [Commanded audit middleware](https://github.com/commanded/commanded-audit-middleware) to store dispatched commands to any Ecto supported database. Doing so will allow you to tie commands and their resultant events together. The correlation id can also be used to associated all related messages, assuming you are copying them when dispatching commands. There's an example of doing so given below.

In Greg's Event Store I think the causation id is copied from event to event, ignoring the intermediate command, since his event store is only storing the events.

---

To assist with monitoring and debugging your deployed application it is useful to track the causation and correlation ids for your commands and events.

- `causation_id` - the UUID of the command causing an event, or the event causing a command dispatch.
- `correlation_id` - a UUID used to correlate related commands/events.

You can set causation and correlation ids when dispatching a command:

    :ok = ExampleRouter.dispatch(command, causation_id: UUID.uuid4(), correlation_id: UUID.uuid4())

When dispatching a command in an event handler, you should copy these values from the event your are processing:

    defmodule ExampleHandler do
      use Commanded.Event.Handler, name: "ExampleHandler"
    
      def handle(%AnEvent{..}, metadata) do
        %{event_id: causation_id, correlation_id: correlation_id} = metadata

        ExampleRouter.dispatch(%ExampleCommand{..},
          causation_id: causation_id,
          correlation_id: correlation_id
        )
      end
    end

    

Commands dispatched by a process manager will be automatically assigned the appropriate causation and correlation ids from the source domain event.
