### ISSUE TITLE
Is there any support for processing retroactive events?

### ISSUE THREAD

**Issue by datafoo** [commanded/commanded#238]
I am using ES + CQRS to build a system that publishes events representing user claims. At any point in time, a user can realize that a past claim was wrong or incorrect. Therefore, a user needs to be able to reject or correct any claim. This is were [Retroactive Event](https://martinfowler.com/eaaDev/RetroactiveEvent.html) comes handy.

However, _Retroactive Event_ requires special processing. Does _commanded_ support it? If not, could it be added?

**Comment by slashdotdash** [comment]
No, retroactive events aren't supported. 

You could potentially implement the approach by directly accessing the event store (using `Commanded.EventStore`) and copying events from one stream to another and apply any modifcation during the copy process. 

The Elixir Event Store and Greg Young's Event Store are both append-only storage. The only way to modify events is to copy them into a new stream. Greg's [Versioning in an Event Sourced System](https://leanpub.com/esversioning) provides some useful strategies for versioning which could be applicable for implementing reactive events (since you want to "rewrite history").
