### ISSUE TITLE
Process Manager listening for unwanted Commands, and creating a junk snapshot.

### ISSUE THREAD

**Issue by henry-hz** [commanded/commanded#25]
When making a simple account creation and deposit, I observed that a snapshot was created even with no process manager command. Notice that the source_uuid [left postgre window] has used the "transfer_uuid" from the DepositMoney command.

![bug-processmanager](https://cloud.githubusercontent.com/assets/1010008/19936247/458f8934-a0f3-11e6-9d8e-9578a222f509.png)

**Comment by henry-hz** [comment]
I am thinking about implementing a FSM data structure, so this kind of problem couldn't happen. 
https://github.com/sasa1977/fsm

Makes sense ? Should I proceed an PR ?

**Comment by slashdotdash** [comment]
Yes, you've discovered an issue in that area. The `Commanded.ProcessManagers.ProcessRouter.continue_process_manager` [function](https://github.com/slashdotdash/commanded/blob/master/lib/commanded/process_managers/process_router.ex#L117) should ensure that when it starts the process manager it is starting a process that has already been created. It the snapshot data for that process must be present.

Feel free to work on a pull request. I use Saša's fsm library in the eventstore.

**Comment by henry-hz** [comment]
Please, add to the roadmap, I still have to study the code to know how to fix this bug

**Comment by slashdotdash** [comment]
It's in the backlog of the [Development roadmap](https://github.com/slashdotdash/commanded/projects/1).

**Comment by Trevoke** [comment]
Is this still known to be an issue?

**Comment by slashdotdash** [comment]
@Trevoke Process managers have two components; a router and many instances. The router subscribes to the event store and routes events to instances, this might require starting a new process or resuming an existing one. A process manager instance will record a snapshot after each event it processes.

I'm in the process of reworking process managers so that they use linked events as their persistence mechanism (event sourcing), with optional state snapshots. That change will resolve this issue.

**Comment by slashdotdash** [comment]
Closed by #181.
