### ISSUE TITLE
NaiveDateTime vs DateTime

### ISSUE THREAD

**Issue by zamith** [commanded/commanded#252]
While the documentation states that `created_at` for `RecordedEvent` is an UTC datetime, it is actually persisted as a NaiveDateTime (as far as I could tell), which does not have a timezone.

I ran into this situation because we are enforcing that timestamps across our system have a timezone, and this can be problematic. Is this a conscious choice, and if so, why?

**Comment by slashdotdash** [comment]
The `created_at` date is a `NaiveDateTime` in UTC timezone. 

I think the reason why I chose `NaiveDateTime` was because it's the default type used by [Ecto's `timestamps` function](https://hexdocs.pm/ecto/Ecto.Schema.html#timestamps/1) when adding inserted at and updated at timestamp fields.

There's a similar issue raised for the EventStore library to migrate from `NaiveDateTime` to `DateTime` ([147](https://github.com/commanded/eventstore/issues/147)). This will be a breaking change for users who use the `created_at` field from an event's metadata anywhere in their app.

**Comment by zamith** [comment]
As far as I know Ecto uses it as a default for backwards compatibility reasons, it would be good to move away from it here. 

Given that it would be a breaking change, is this something you'd still be willing to do as part of a major release, or not part of the plans at all?

**Comment by slashdotdash** [comment]
I don't have an issue with migrating to `DateTime` if that's what people would prefer to use.

**Comment by slashdotdash** [comment]
Fixed by #254.
