### ISSUE TITLE
Access Aggregate state

### ISSUE THREAD

**Issue by edgarjrg** [commanded/commanded#271]
Hello! first of all thank you for such a nice framework 👏 great work to all 🔥 

My questions is regarding on how can i access one aggregate state at any point, including other aggregates, as aggregates are referenced between each other (not necesary by reference but by an property)

Thank you in advance 🙏

**Comment by slashdotdash** [comment]
@edgarjrg You can access an aggregate's state using the [`Aggregate.aggregate_state/3` function](https://github.com/commanded/commanded/blob/f25bfa451cc382c34407457b5357d0b2f0cdfc51/lib/commanded/aggregates/aggregate.ex#L125) which you pass the aggregate module and aggregate identity:

```elixir
%BankAccount{...} = Aggregate.aggregate_state(BankAccount, account_number)
```
However this function is not documented because it shouldn't be used outside of tests because an aggregate's state should be an internal implementation detail, not used for querying. 

Instead, in a CQRS application all state must be derived from the published domain events. Usually this would be a projection into a read model built for querying. You can use [Commanded Ecto projections](https://github.com/commanded/commanded-ecto-projections) to project events into a SQL database. If an aggregate needs data owned by another aggregate then you should lookup the data from a projection and include it in the command before dispatch. This prevents tight coupling between aggregate instances, such as querying for their state, and ensures their state isn't exposed.

**Comment by edgarjrg** [comment]
Thank you very much! in the first case (access aggregate state from any point) was precisely for testing purposes. And for the second case i was still unsure of the "Commanded" way to do it, but now is clear (access projections)!

Thank you very much for the quick answer 👏

**Comment by slashdotdash** [comment]
Accessing aggregate state for test purposes should be included in the aggregate guide and/or testing documentation.
