### ISSUE TITLE
Feedback: Commanded / Conduit

### ISSUE THREAD

**Issue by andyl** [commanded/commanded#285]
I'm a new Commanded developer - maybe my perspective will be of interest to old-timers.

Commanded has been on my radar screen for 18 months.  But prior to today, I thought the name of the framework was 'Conduit'.  I've seen more presentations, books etc. related to "Building Conduit" than "Commanded".  And the names (Conduit/Commanded) are somewhat similar, causing me as a casual onlooker to confuse the two.  I send a note to my buddy the other day "you should check out conduit"...

Probably it's just me.  But next time there was an opportunity to rewrite, I'd replace the title "Building Conduit" with "Activity Tracking using Commanded" or some such.

**Comment by slashdotdash** [comment]
Thanks for the feedback @andyl. 

The reason why the book is called "Building Conduit" and sample repo "Conduit" is because it is a back-end  implementation of the [RealWorld example app](https://github.com/gothinkster/realworld) which goes by the same name. By following the REST API contract defined in the RealWorld project means that you can combine the Elixir CQRS/ES back-end with any of the compatible front-ends (React, Angular, Elm, Vuew, et al.). 

It also meant that I didn't need to worry about writing any front-end code myself to build and demo a working app. Another reason was that it you can also compare an event sourced approach to building the back-end vs. a more traditional CRUD approach (such as this [Phoenix](https://github.com/gothinkster/elixir-phoenix-realworld-example-app) example).

**Comment by andyl** [comment]
Yeah I get that.  Well you have my feedback and you're free to use or not.  The book and app are great BTW, title notwithstanding.  Just watched your video 'event sourcing in practice' and the eventstorming technique with colored squares is nice - going to adopt.
