### ISSUE TITLE
[Doc] Guide to replaying events 

### ISSUE THREAD

**Issue by jnatherley** [commanded/commanded#316]
Hello,

I've been using Commanded for the last few months and i've read in various places about replaying events. Would it be possible to create a guide on how to correctly replay events when using projections?

I've tried using the current documentation in my local development machine, but the projections are never re-created. What needs to be reset? Which order?

**Comment by slashdotdash** [comment]
Have you seen the [Rebuilding a projection](https://github.com/commanded/commanded-ecto-projections/blob/master/guides/Usage.md#rebuilding-a-projection) section from Commanded Ecto projections? 

To reset a projection you need to both reset the event store subscription and reset the projection. Do the following while the app is not currently running:

1. Delete the row containing the last seen event for the projection name:

    ```sql
    -- Read store database
    delete from projection_versions
    where projection_name = 'example_projection';
    ```

2. Truncate the table(s) that are being populated by the projection, and restart their identity:

    ```sql
    -- Read store database
    truncate table example_projections
    restart identity;
    ```

3. Reset the projector's event store subscription:

    ```sql
    -- Event store database
    DELETE FROM subscriptions
    WHERE stream_uuid = '$all' AND subscription_name = 'example_projection';
    ```

Commanded also provides the [`commanded.reset` mix task](https://hexdocs.pm/commanded/Mix.Tasks.Commanded.Reset.html) to reset a running event handler (e.g. a projector).  Which can be used instead of step 3 above.

**Comment by jnatherley** [comment]
Ah perfect, I'll give that another try later. In my last attempt i managed to get the events to replay, but the projections were not recreated (Makes sense now since the app was running and probably had the state in memory).
