### ISSUE TITLE
How to implement event undo?

### ISSUE THREAD

**Issue by Rockson** [commanded/commanded#323]
So there is a command that I want the user to be able to undo. Let's say I have a renameUser command. To implement the undo command I would need a reference to the last renameUser event and the state of the aggregate before that event. How can I achieve this?
Or is there another approach?

**Comment by trbngr** [comment]
Can you just store the previous username in your `UserRenamed` event, pop it in a database, and dispatch a new `RenameUser`?

**Comment by fdbeirao** [comment]
@Rockson Just giving my two cents here: from your application's point of view, this is a new feature. I am not 100% sure if the infrastructure should be the one powering this particular feature, even if "undo" could sound like something that your CQRS/ES infrastructure would provide.

Here's how I would go about it: remember in your aggregate/entity internal state this `PreviousUsername`. Then, when this new "undo" command comes, you are already holding in your state what the undo should undo into. And this is backwards compatible, because if you re-interpret your entire stream of events, you get to the correct state.

Which begs the question: will this feature only support one undo? Is it a stack of undos? You can think about these questions in the context of your requirements.

Let me know if this helps. Cheers and good luck! 👍🏻

**Comment by Rockson** [comment]
Thanks for your answers, yeah as you pointed out there is no need for the infrastructure to provide such functionality.

So if I understood correctly, what you are suggesting is placing the data that the undo command needs either in the read model or in the aggregate itself?
If I had to choose I would place it in the aggregate since it would be easier(no need for projection and to retrieve it manually from the read model) but as the aggregate grows it could be a performance/space issue maybe?

**Comment by fdbeirao** [comment]
The way I see it, the decision to keep the data in the aggregate or to obtain it from a read model is one of Strong vs Weak consistency: 

* If the data is kept in the aggregate, it is guaranteed that the next command coming in already has that data (1st command: Rename, 1 second later: UndoRenameCommand).
* If the data is obtained from the Read Model, then it might be the case that the projections haven't been updated, and the UndoRenameCommand goes back "one version too many".

You still need to think: do you only support one UndoRename? (which is a perfectly valid scenario!)
Or you could support multiple undos (by keeping a stack/list in the aggregate). Your choice.

Regarding aggregate growing, performance/space issues, you can keep those in check by setting a limit on how many "undos" you support: 1.. 5.. 10? If you truncate that stack to a maximum, then you always know how much the aggregate state can grow.

Best of luck 🤞

**Comment by slashdotdash** [comment]
@Rockson It might be worth considering how version control such as Git handles "undo" operations. To undo a commit you revert the commit. Git will create a _new commit_ with the inverse of the reverted commit. This new commit is added to the branch history which allows you to undo the revert commit, etc.

To undo an incorrect `UserRenamed` event you would want to produce a corresponding `UserRenameUndone` or `UserRenameReverted` event. To support undo of any user operation you would need to define "undo" events which revert the changes of each operation's associated event(s). 

A generic "undo the last operation" command could be implemented by having the aggregate track an ordered list of its events in its state. Then it would take the last applied event from its state and map to its appropriate reverted event.  You might even be able to suppprt "undo the last X operations" by going back X events and reverting each.

**Comment by Rockson** [comment]
That's clearer now, thanks all for your help!
