### ISSUE TITLE
Consistency Issue

### ISSUE THREAD

**Issue by jodyalbritton** [commanded/commanded#337]
In my Phoenix app I have implemented some features after following the Conduit guide and book. In my App.dispatch I have consistency to strong. In my projector I also have consistency to strong. 

```
with :ok <- App.dispatch(create_location), consistency: :strong do
      get(Location, uuid)
else
```

The problem is that the projection is not updated before the command returns which logs an error. 

`all plugs must receive a connection (conn) and return a connection, got: {:error, :not_found}`

**Comment by slashdotdash** [comment]
@jodyalbritton In the code snippet you included the `consistency: :strong` option is not being passed to the dispatch call because it is outside the brackets. I’m not sure whether that’s a simple copy & paste error, or the cause of your issue?

You could try running the Conduit sample repo locally which is configured to use strong consistency for read model projections and see whether that is working for you.

**Comment by jodyalbritton** [comment]
@slashdotdash Thank you. That solved it.
