### ISSUE TITLE
Support Custom State for Event Handlers?

### ISSUE THREAD

**Issue by larskluge** [commanded/commanded#366]
Background: We are building a platform to support multiple e-commerce stores. Each store needs to sync some of its data to an external source/API. Each store should run independently from each other, a failure in some store should not impact any other store. Therefore each store (variable number on our platform) should have one event handler to sync data. 

Each selected event in the stream needs to successfully be sync'd with the external API before moving on to the next event in order to guarantee successful processing & correct order. 

Issue: `Commanded.Event.Handler` does not support custom state to be passed upon start up all the way down to `handle` to allow filter & process of the correct events in order to accomplish the sync per store in our case. Nor a dynamic `name` to support multiple processes of the same event handler module. 

Some rough code idea: 

```elixir
defmodule Sync do
  use Commanded.Event.Handler, application: App, ...
  def handle(%AnEvent{..}, %{state: %{store: "foo"}} = _metadata), do: ...
end

Sync.start_link(name: "Sync#foo", store: "foo")
```

Would something like this make sense to be supported? Can I accomplish my objective differently?

Thank you!

**Comment by slashdotdash** [comment]
@larskluge Adding support for starting dynamically named event handlers and providing custom state is definitely a useful feature that could be added. It likely wouldn't require too much effort to implement and the example you provide where the state is included in the metadata means it won't be a breaking change.

As a side note, how many tenants do you need to support: 10s, 100s, 1,000s? The reason for asking is because the next Commanded (and EventStore) releases have support for starting dynamic Commanded applications (#324). This would allow you to start a separate Commanded application and event handlers dynamically for each tenant. They can even be started and stopped at runtime. However, this approach is only really suitable when you have a limited number of tenants (in the 10s - 100s).

**Comment by larskluge** [comment]
In the 10s - 100s, but growing.. still will take quite some time to reach 1,000s, I believe. 

Also, thinking about `init/0`, it might be the right approach to align it with `GenServer` to allow modifying its initial state: 

```elixir
def init(start_up_args) do
  state = start_up_args |> *magic*
  {:ok, state}
end
```

Dynamic Commanded applications sounds interesting. It could either be a really interesting feature for us, or we might not end up using it. I have to wrap my head around its implications :)

Would a event handler know in which dynamic application its started?
