### ISSUE TITLE
Consistency timeout when starting multiple dynamic commanded applications

### ISSUE THREAD

**Issue by hwenyi** [commanded/commanded#395]
I found this issue when trying to implement dynamic commanded applications for our project. It seems like when there is more than one dynamic app running, apps that are started later will experience consistency timeout for almost every command, while the first app would remain stable.
And the reason for consistency timeout seems to because, by the time consistency guarantee middleware tries to check if events are handled by all subscriptions, the info hasn't been updated in the streams_table yet while it should have been handled.

This is a sample app that replicated the issue I found: https://github.com/hwenyi/dynamic_cmd

**Comment by slashdotdash** [comment]
I've finally been able to take a look at this and have tracked down the root cause. It is because the event store schema is being shared between the dynamic Commanded applications. This causes a problem because the event store subscriptions only allow a single named subscriber. 

When you start an event handler or process manager per dynamic application they will attempt to subscribe to the event store using the same name. The event store ensures only one named subscription will be connected and process events. Thus any handlers started for the second, third, etc. dynamic Commanded application will not be able to subscribe to the event store.

There are two ways to resolve this issue:

1. Use a separate event store database or Postgres schema for each dynamic application. 

    This will work because the identically named event store subscriptions will be tracked in the subscriptions table within the separate schemas. I have sent you a [pull request](https://github.com/hwenyi/dynamic_cmd/pull/1) with this fix in place.

2. Use the same event store database for all dynamic applications but define the event handler and process manager names at runtime so that they are uniquely named (e.g. by adding a dynamic suffix to their names).

    Support for runtime event handler and process manager names was recently added (#396) and has not yet been released.
