### ISSUE TITLE
How to handle changes/versioning in events, more or less like migrations?

### ISSUE THREAD

**Issue by roehst** [commanded/commanded#434]
Hi, I have a question which I must answer before choosing commanded.

If I change my commands or event models, how to I handle the old events? How to I work with versioning in Event Sourcing?

TKs guys, project looks awesome

**Comment by davydog187** [comment]
@roehst that is quite a big question. If you need to change events, you can implement the [Upcaster Protocol](https://hexdocs.pm/commanded/Commanded.Event.Upcaster.html), which you can use to migrate events per your needs.

There is some documentation to check out as well https://hexdocs.pm/commanded/events.html#upcasting-events

Beyond that, you may want to look into Event lifecycle management, tooling for truncating old events, etc. Commanded provides a lot

**Comment by slashdotdash** [comment]
Greg Young has written a book on the subject which is free to read online and includes a number of strategies. 

* [Versioning in an Event Sourced System](https://leanpub.com/esversioning).

**Comment by slashdotdash** [comment]
By default the events written to the database using the Postgres EventStore are immutable. They cannot be updated or deleted due to rules on the tables. However, as a means of last resort you could drop these rules and then edit the events as needed. This is easier to achieve if you use Postgres’ built in support for JSON via the `jsonb` column type.

**Comment by roehst** [comment]
@davydog187 , @slashdotdash thank you very much for the references.

I will look into that before asking for further help. Thanks a lot.
